[package]
name = "toy-raytracer-rust"
version = "0.1.0"
authors = ["yufeiliu94@gmail.com"]
edition = "2018"

[features]
single-precision = []

[dependencies]
clap = "3.0.0-beta.2"
num_cpus = "1.13.0"
pbr = "1.0.4"
png = "0.16.8"
rand = "0.8.4"
rayon = "1.5.1"